name: Node.js Package

on:
  pull_request:
    branches: [master]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git config --global user.name "WATANABE Shin"
      - run: git config --global user.email "sin9270@gmail.com"
      - run: git fetch origin develop
      - run: git checkout develop
      - run: npm version patch
      - run: git push origin HEAD
